apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls-cert
  namespace: argocd
spec:
  secretName: argocd-tls
  dnsNames:
    - "argocd.cis240470.projects.jetstream-cloud.org"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer