repositories:
  - name: sealed-secrets
    url: https://bitnami-labs.github.io/sealed-secrets
  - name: cloud-provider-openstack
    url: https://kubernetes.github.io/cloud-provider-openstack
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jetstack
    url: https://charts.jetstack.io
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: sealed-secrets
    chart: sealed-secrets/sealed-secrets
    namespace: kube-system
  - name: os-cloud-controller
    chart: cloud-provider-openstack/openstack-cloud-controller-manager
    values: 
      - ./values/os-cloud-controller.yaml
  - name: os-cinder-csi
    chart: cloud-provider-openstack/openstack-cinder-csi
    values: 
      - ./values/os-cinder-csi.yaml
  - name: external-dns
    chart: bitnami/external-dns
    values: 
      - ./values/external-dns.yaml
  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: cert-manager
    values: 
      - ./values/cert-manager.yaml
  - name: designate-certmanager-webhook
    chart: ./charts/designate-certmanager-webhook
    namespace: cert-manager
    values:
      - ./values/designate-certmanager-webhook.yaml
  - name: argocd
    chart: argo/argo-cd
    namespace: argocd
    values:
      - ./values/argocd.yaml
  - name: argocd-apps
    chart: argo/argocd-apps
    namespace: argocd
    values:
      - ./values/argocd-apps.yaml
  - name: argocd-image-updater
    chart: argo/argocd-image-updater
    namespace: argocd
  - name: addons
    chart: "../addons"