apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/master/manifests/controller-manager/cloud-controller-manager-roles.yaml
  - https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/master/manifests/controller-manager/cloud-controller-manager-role-bindings.yaml
  - https://raw.githubusercontent.com/kubernetes/cloud-provider-openstack/master/manifests/controller-manager/openstack-cloud-controller-manager-ds.yaml

patches:
  - target:
      kind: DaemonSet
      name: openstack-cloud-controller-manager
    patch: |
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          # This allows us to host the openstack cloud controller manager on the control plane nodes
          node-role.kubernetes.io/control-plane: "true" 