apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-tls-cert
  namespace: keycloak
spec:
  secretName: keycloak-tls
  dnsNames:
    - "keycloak.cis240470.projects.jetstream-cloud.org"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer