apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak
  namespace: keycloak
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`keycloak.cis240470.projects.jetstream-cloud.org`)
      priority: 10
      services:
        - name: keycloak
          port: 8080