apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/keycloak/keycloak-quickstarts/refs/heads/main/kubernetes/keycloak.yaml
  - ingress.yaml

patches:
  - target:
      name: keycloak
      kind: Service
    patch: |-
      - op: replace
        path: /spec/type
        value: ClusterIP