apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headlamp
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`dashboard.cis240470.projects.jetstream-cloud.org`)
      priority: 10
      services:
        - name: headlamp
          port: 80
  tls:
    secretName: headlamp-tls