apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headlamp
  namespace: kube-system
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`dashboard.cis240470.projects.jetstream-cloud.org`)
      priority: 10
      services:
        - name: headlamp
          port: 80