apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-dashboard-cert
  namespace: kube-system
spec:
  secretName: traefik-dashboard-tls
  dnsNames:
    - "argocd.cis240470.projects.jetstream-cloud.org"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer